export const astroData = [
  {
    id: 1,
    imgLink: "https://m.media-amazon.com/images/I/61i-4zISDBS._AC_SX466_.jpg",
    experience: "10+Years",
    name: "Astrologer Ramraj",
    specialities: "Love, Bussiness, Life",
    skills: "Vedic Astrology, Kundali",
    price: "₹10/min",
    status: "online",
  },
  {
    id: 2,
    imgLink:
      "https://www.jacketmakers.com/wp-content/uploads/2022/10/juan-ruiz-jacket-768x896.jpg",
    experience: "10+Years",
    name: "Astrologer Ramraj",
    specialities: "Love, Bussiness, Life",
    skills: "Vedic Astrology, Kundali",
    price: "₹10/min",
    status: "online",
  },
  {
    id: 3,
    imgLink:
      "https://fair-aesthetic-team.de/wp-content/uploads/2021/01/timothy-barlin-FGaknWvNbBk-unsplash-768x1152.jpg",
    experience: "10+Years",
    name: "Astrologer Ramraj",
    specialities: "Love, Bussiness, Life",
    skills: "Vedic Astrology, Kundali",
    price: "₹10/min",
    status: "online",
  },
  {
    id: 4,
    imgLink:
      "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT8MaSOmrNEZ92DJMxDdf_pgxdY3z_3iYMM4L3OSpSEobRRRng8",
    experience: "10+Years",
    name: "Astrologer Ramraj",
    specialities: "Love, Bussiness, Life",
    skills: "Vedic Astrology, Kundali",
    price: "₹10/min",
    status: "online",
  },
  {
    id: 5,
    imgLink:
      "https://img.ltwebstatic.com/images3_pi/2021/05/17/16212242335e939d6b003346dbbf921466b7bdfeb4_thumbnail_900x.webp",
    experience: "10+Years",
    name: "Astrologer Ramraj",
    specialities: "Love, Bussiness, Life",
    skills: "Vedic Astrology, Kundali",
    price: "₹10/min",
    status: "online",
  },
  {
    id: 6,
    imgLink:
      "https://images.unsplash.com/photo-1617922001439-4a2e6562f328?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    experience: "10+Years",
    name: "Astrologer Ramraj",
    specialities: "Love, Bussiness, Life",
    skills: "Vedic Astrology, Kundali",
    price: "₹10/min",
    status: "online",
  },
  {
    id: 7,
    imgLink:
      "https://tse2.mm.bing.net/th?id=OIP.JX-HlEO7S0du7tSiO2VQGgHaJQ&pid=Api&P=0",
    experience: "10+Years",
    name: "Astrologer Ramraj",
    specialities: "Love, Bussiness, Life",
    skills: "Vedic Astrology, Kundali",
    price: "₹10/min",
    status: "online",
  },
  {
    id: 8,
    imgLink:
      "https://img.freepik.com/free-photo/handsome-young-man-sitting-isolated-grey_171337-10550.jpg?size=626&ext=jpg",
    experience: "10+Years",
    name: "Astrologer Ramraj",
    specialities: "Love, Bussiness, Life",
    skills: "Vedic Astrology, Kundali",
    price: "₹10/min",
    status: "online",
  },
  {
    id: 9,
    imgLink:
      "https://www.wallpaperup.com/uploads/wallpapers/2014/11/20/522039/b9f14a10741bc0c6d88f3d262191b876.jpg",
    experience: "10+Years",
    name: "Astrologer Ramraj",
    specialities: "Love, Bussiness, Life",
    skills: "Vedic Astrology, Kundali",
    price: "₹10/min",
    status: "online",
  },
];
